---
- name: "Download packer"
  get_url: url=https://dl.bintray.com/mitchellh/packer/0.5.2_linux_386.zip
           dest=/tmp/packer-0.5.2_linux_386.zip
           sha256sum=114b6ea3c623a048552d1464a34866f6d9738a3a5dcf62e606ced60c8958619f

- name: "Install packer"
  unarchive: src=/tmp/packer-0.5.2_linux_386.zip dest=/usr/local/bin copy=no
